# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [3]:
import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix


(True,
 array([[2.+0.j, 2.-1.j],
        [2.+1.j, 3.+0.j]]))


## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [4]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


(True,
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.        +0.70710678j, -0.        -0.70710678j]]))

# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [5]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v


array([ -7.+16.j,  -9.+22.j,  -9.+38.j, -11.+52.j])


## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [6]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[-11. +28.j, -13. +34.j, -13. +66.j, -15. +80.j],
       [-15. +40.j, -17. +46.j, -17. +94.j, -19.+108.j],
       [-15.+104.j, -17.+126.j, -17.+142.j, -19.+172.j],
       [-19.+148.j, -21.+170.j, -21.+202.j, -23.+232.j]])

# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

In [7]:
import numpy as np

# Define the matrix
H = np.array([[3, 2+1j], [2-1j, 1]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(H, H.conj().T)

# Calculate the eigenvalues if the matrix is Hermitian
eigenvalues = np.linalg.eigvals(H) if is_hermitian else None

print("Matrix:\n",H)
print("Is hermitian?:",is_hermitian)
print("Eigen values:",eigenvalues)

Matrix:
 [[3.+0.j 2.+1.j]
 [2.-1.j 1.+0.j]]
Is hermitian?: True
Eigen values: [ 4.44948974-5.06745162e-17j -0.44948974+5.06745162e-17j]


## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

In [26]:
import numpy as np

# Define the matrix
U = np.array([[1/np.sqrt(2), 1j/np.sqrt(2)], [1j/np.sqrt(2), 1/np.sqrt(2)]])
# Check if the matrix is Unitary
U_dagger = U.conj().T
is_unitary = np.allclose(np.dot(U, U_dagger), np.eye(2))

print("Is unitary?:",is_unitary)
print("Matrix U†: \n",U_dagger)
print("Matrix U: \n",U)

Is unitary?: True
Matrix U†: 
 [[0.70710678-0.j         0.        -0.70710678j]
 [0.        -0.70710678j 0.70710678-0.j        ]]
Matrix U: 
 [[0.70710678+0.j         0.        +0.70710678j]
 [0.        +0.70710678j 0.70710678+0.j        ]]


## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

In [24]:
import numpy as np

# Define two complex vectors for the tensor product
v = np.array([1+1j, 2-1j])
w = np.array([1-2j, 3])

# Calculate the tensor product
tensor_product = np.kron(v, w)

print("Vector V: ",v)
print("Vector W: ",w)
print("Tensor product V ⊗ W: ",tensor_product)

Vector V:  [1.+1.j 2.-1.j]
Vector W:  [1.-2.j 3.+0.j]
Tensor product V ⊗ W:  [3.-1.j 3.+3.j 0.-5.j 6.-3.j]


## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

In [25]:
import numpy as np

# Define the matrices
M1 = np.array([[0, 1], [1, 0]])
M2 = np.array([[1j, 0], [0, -1j]])

# Calculate the tensor product
tensor_product = np.kron(M1, M2)

print("Matrix M1: \n",M1)
print("Matrix M2: \n",M2)
print("Tensor product M1 ⊗ M2: \n",tensor_product)

Matrix M1: 
 [[0 1]
 [1 0]]
Matrix M2: 
 [[ 0.+1.j  0.+0.j]
 [ 0.+0.j -0.-1.j]]
Tensor product M1 ⊗ M2: 
 [[0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]]


## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

In [54]:
import numpy as np

# Define the input state
input_state = np.array([1, 0])

# Define the beamsplitter matrix H
beamsplitter = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
# Define the mirror matrix X
phase_shift = np.array([[0, 1], [1, 0]])

# Calculate the output state
y1 = np.dot(beamsplitter, input_state)
y2 = np.dot(phase_shift, y1)
y3 = np.dot(beamsplitter, y2) 

print("Beamsplitter matrix H: \n",beamsplitter)
print("Mirror matrix X: \n",phase_shift)
print("\n")
print("Input_state (y0): ",input_state)
print("y1: ",y1)
print("y2: ",y2)
print("Output state (y3): ", "[",round(y3[0],2), round(y3[1],2),"]")

Beamsplitter matrix H: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Mirror matrix X: 
 [[0 1]
 [1 0]]


Input_state (y0):  [1 0]
y1:  [0.70710678 0.70710678]
y2:  [0.70710678 0.70710678]
Output state (y3):  [ 1.0 0.0 ]


## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)

In [64]:
#Set up the algorithm of Deutsch's problem

import numpy as np

# Define the input state
input_state1 = np.array([1, 0])
input_state2 = np.array([0, 1])
# Define the oracle matrix Uf
Uf = np.array([[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
# Define the beamsplitter matrix H
beamsplitter = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
# Define the identity matrix I
I = np.eye(2)

# Calculate the output state
y0 = np.kron(input_state1, input_state2)
y1 = np.dot(np.kron(beamsplitter, beamsplitter), y0)
y2 = np.dot(Uf,y1)
y3 = np.dot(np.kron(beamsplitter, I), y2)

# Calculate probabilities for measuring 0 and 1 in the first qubit
prob_0 = np.abs(y3[0])**2 + np.abs(y3[1])**2
prob_1 = np.abs(y3[2])**2 + np.abs(y3[3])**2

# Normalize probabilities
total_prob = prob_0 + prob_1
prob_0 /= total_prob
prob_1 /= total_prob

measured_state = np.array([prob_0, prob_1])

print("Oracle matrix Uf: \n", Uf)
print("Beamsplitter matrix H: \n", beamsplitter)

print("Input_state (y0): ", y0)
print("y1: ", y1)
print("y2: ", y2)
print("Output state (y3): ", y3)
print("Measured state probabilities [|0⟩, |1⟩]: ", measured_state)

# Determine if the function is constant or balanced
if np.isclose(prob_0, 1, atol=1e-6):
    print("The function is constant")
elif np.isclose(prob_1, 1, atol=1e-6):
    print("The function is balanced")
else:
    print("Unexpected result")

Oracle matrix Uf: 
 [[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Beamsplitter matrix H: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Input_state (y0):  [0 1 0 0]
y1:  [ 0.5 -0.5  0.5 -0.5]
y2:  [-0.5  0.5  0.5 -0.5]
Output state (y3):  [ 0.          0.         -0.70710678  0.70710678]
Measured state probabilities [|0⟩, |1⟩]:  [0. 1.]
The function is balanced
